---

# Create action asserts
# ======================

- name: Test "db_list" creation parameter contents
  ansible.builtin.assert:
    that:
      - item.db_owner is defined
      - item.db_owner is string
      - item.template is defined
      - item.template is string
      - item.description is defined
      - item.description is string
      - item.collate is defined
      - item.collate is string
      - item.ctype is defined
      - item.ctype is string
    quiet: true
  loop: "{{ db_list }}"
  loop_control:
    label: "{{ item.db_name }}"
  tags:
    - assert
    - create
    - replace


- name: Test "db_list['db_roles']" parameter
  ansible.builtin.assert:
    that:
      - item.db_roles is defined
      - item.db_roles is iterable
    quiet: true
  loop: "{{ db_list }}"
  loop_control:
    label: "{{ item.db_name }}"
  tags:
    - assert
    - create
    - replace


- name: Test "db_list['db_roles']" parameter contents
  ansible.builtin.assert:
    that:
      - item.1 is defined
      - item.1 is string
    quiet: true
  loop: "{{ db_list | subelements('db_roles') }}"
  loop_control:
    label: "{{ item.0.db_name }} -> {{ item.1 }}"
  tags:
    - assert
    - create
    - replace


- name: Test 'predefined_cluster_roles' parameter
  ansible.builtin.assert:
    that:
      - predefined_cluster_roles is defined
      - predefined_cluster_roles is iterable
    quiet: true
  tags:
    - assert
    - create
    - restore
    - replace


- name: Test '_db_name_suffix' parameter
  ansible.builtin.assert:
    that:
      - _db_name_suffix is defined
      - _db_name_suffix is string
    quiet: true
  tags:
    - assert
    - restore
    - replace
