---

# Extend action asserts
# ======================

- name: Test "db_list['db_extensions']" parameter
  ansible.builtin.assert:
    that:
      - item.db_extensions is defined
      - item.db_extensions is iterable
    quiet: true
  loop: "{{ db_list }}"
  loop_control:
    label: "{{ item.db_name }}"
  tags:
    - assert
    - extend
    - create
    - restore
    - replace


- name: Test "db_list['db_extensions'] parameter contents"
  ansible.builtin.assert:
    that:
      - item.1 is defined
      - item.1 is string
    quiet: true
  loop: "{{ db_list | subelements('db_extensions') }}"
  loop_control:
    label: "{{ item.0.db_name }} -> {{ item.1 }}"
  tags:
    - assert
    - extend
    - create
    - restore
    - replace
