---

# Restore action asserts
# =======================

- name: Test 'source_name' parameter
  ansible.builtin.assert:
    that:
      - item.source_name is defined
      - item.source_name is string
      - item.source_name is regex( "^(.+)\/([^\/]+)$" )
    quiet: true
  loop: "{{ db_list }}"
  loop_control:
    label: "{{ item.db_name }}"
  tags:
    - assert
    - restore
    - replace


- name: Test 'dump_time_frames' parameter
  ansible.builtin.assert:
    that:
      - dump_time_frames is defined
      - dump_time_frames['duration_timeout'] is defined
      - dump_time_frames['poll_interval'] is defined
      - dump_time_frames['duration_timeout'] is number
      - dump_time_frames['poll_interval'] is number
    quiet: true
  tags:
    - assert
    - restore
    - replace


- name: Test '_db_name_suffix' parameter
  ansible.builtin.assert:
    that:
      - _db_name_suffix is defined
      - _db_name_suffix is string
    quiet: true
  tags:
    - assert
    - restore
    - replace
