---

# Install databases extensions
# =============================

- name: Debug '_db_name_suffix' in extend.yml
  debug:
    msg: "{{ _db_name_suffix }}"
  tags:
    - never


- name: Asserts for extend actions
  include_tasks:
    file: asserts/extend.yml
  tags:
    - assert
    - extend
    - create
    - restore
    - replace


- name: "CREATE EXTENSION IF NOT EXISTS db_extensions SCHEMA public;"
  postgresql_query:
    db: "{{ item.0.db_name + _db_name_suffix }}"
    query: 
      "{{ install_extension_query | format( item.1 ) }}"
  loop: 
    "{{ db_list | subelements('db_extensions') }}"
  loop_control:
    label: "{{ item.0.db_name + _db_name_suffix }} -> {{ item.1 }}"
  tags:
    - extend
    - create
    - restore
    - replace
